# Generated by Django 5.1.4 on 2024-12-29 23:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unique_key',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
