# Generated by Django 5.1.4 on 2024-12-29 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalog', '0003_product_stock'),
        #('orders', '0009_alter_order_user'),
        ('users', '0004_customuser_profile_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
